/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var a=this||self,b=function(f,k){f=f.split(".");var e=a;f[0]in e||"undefined"==typeof e.execScript||e.execScript("var "+f[0]);for(var g;f.length&&(g=f.shift());)f.length||void 0===k?e=e[g]&&e[g]!==Object.prototype[g]?e[g]:e[g]={}:e[g]=k};var c={fa:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},ea:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}},d=c;d=c;var h={ma:"y",ta:"y G",na:"MMM y",oa:"MMMM y",ua:"MM/y",ha:"MMM d",ia:"MMMM dd",ka:"M/d",ja:"MMMM d",ra:"MMM d, y",la:"EEE, MMM d",sa:"EEE, MMM d, y",ga:"d",qa:"MMM d, h:mm\u202fa zzzz"},l=h;l=h;var m={u:["BC","AD"],s:["Before Christ","Anno Domini"],I:"JFMAMJJASOND".split(""),V:"JFMAMJJASOND".split(""),G:"January February March April May June July August September October November December".split(" "),U:"January February March April May June July August September October November December".split(" "),R:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),X:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ba:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
Z:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),T:"Sun Mon Tue Wed Thu Fri Sat".split(" "),Y:"Sun Mon Tue Wed Thu Fri Sat".split(" "),J:"SMTWTFS".split(""),W:"SMTWTFS".split(""),S:["Q1","Q2","Q3","Q4"],O:["1st quarter","2nd quarter","3rd quarter","4th quarter"],g:["AM","PM"],i:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],aa:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],j:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],A:6,ca:[5,6],B:5};
m={u:["BC","AD"],s:["before Christ","Anno Domini"],I:"JFMAMJJASOND".split(""),V:"JFMAMJJASOND".split(""),G:"January February March April May June July August September October November December".split(" "),U:"January February March April May June July August September October November December".split(" "),R:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),X:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ba:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
Z:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),T:"Sun Mon Tue Wed Thu Fri Sat".split(" "),Y:"Sun Mon Tue Wed Thu Fri Sat".split(" "),J:"SMTWTFS".split(""),W:"SMTWTFS".split(""),S:["Q1","Q2","Q3","Q4"],O:["1st quarter","2nd quarter","3rd quarter","4th quarter"],g:["a.m.","p.m."],i:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],aa:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],j:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],A:6,ca:[5,
6],B:5};var n={m:".",C:",",K:"%",da:"0",N:"+",F:"-",v:"E",M:"\u2030",D:"\u221e",H:"NaN",l:"#,##0.###",P:"#E0",L:"#,##0%",h:"\u00a4#,##0.00",o:"USD"};n={m:".",C:",",K:"%",da:"0",N:"+",F:"-",v:"E",M:"\u2030",D:"\u221e",H:"NaN",l:"#,##0.###",P:"#E0",L:"#,##0%",h:"\u00a4#,##0.00",o:"CAD"};b("I18N_DATETIMESYMBOLS_ERAS",m.u);b("I18N_DATETIMESYMBOLS_ERANAMES",m.s);b("I18N_DATETIMESYMBOLS_NARROWMONTHS",m.I);b("I18N_DATETIMESYMBOLS_STANDALONENARROWMONTHS",m.V);b("I18N_DATETIMESYMBOLS_MONTHS",m.G);b("I18N_DATETIMESYMBOLS_STANDALONEMONTHS",m.U);b("I18N_DATETIMESYMBOLS_SHORTMONTHS",m.R);b("I18N_DATETIMESYMBOLS_STANDALONESHORTMONTHS",m.X);b("I18N_DATETIMESYMBOLS_WEEKDAYS",m.ba);b("I18N_DATETIMESYMBOLS_STANDALONEWEEKDAYS",m.Z);b("I18N_DATETIMESYMBOLS_SHORTWEEKDAYS",m.T);
b("I18N_DATETIMESYMBOLS_STANDALONESHORTWEEKDAYS",m.Y);b("I18N_DATETIMESYMBOLS_NARROWWEEKDAYS",m.J);b("I18N_DATETIMESYMBOLS_STANDALONENARROWWEEKDAYS",m.W);b("I18N_DATETIMESYMBOLS_SHORTQUARTERS",m.S);b("I18N_DATETIMESYMBOLS_QUARTERS",m.O);b("I18N_DATETIMESYMBOLS_AMPMS",m.g);b("I18N_DATETIMESYMBOLS_DATEFORMATS",m.i);b("I18N_DATETIMESYMBOLS_TIMEFORMATS",m.aa);b("I18N_DATETIMESYMBOLS_DATETIMEFORMATS",m.j);b("I18N_DATETIMESYMBOLS_FIRSTDAYOFWEEK",m.A);b("I18N_DATETIMESYMBOLS_WEEKENDRANGE",m.ca);
b("I18N_DATETIMESYMBOLS_FIRSTWEEKCUTOFFDAY",m.B);b("I18N_DATETIMEPATTERNS_YEAR_FULL",l.ma);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_ABBR",l.na);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_FULL",l.oa);b("I18N_DATETIMEPATTERNS_MONTH_DAY_ABBR",l.ha);b("I18N_DATETIMEPATTERNS_MONTH_DAY_FULL",l.ia);b("I18N_DATETIMEPATTERNS_MONTH_DAY_SHORT",l.ka);b("I18N_DATETIMEPATTERNS_MONTH_DAY_MEDIUM",l.ja);b("I18N_DATETIMEPATTERNS_WEEKDAY_MONTH_DAY_MEDIUM",l.la);b("I18N_DATETIMEPATTERNS_DAY_ABBR",l.ga);
void 0!==m.pa&&b("I18N_DATETIMESYMBOLS_ZERODIGIT",m.pa);b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_SEP",n.m);b("I18N_NUMBERFORMATSYMBOLS_GROUP_SEP",n.C);b("I18N_NUMBERFORMATSYMBOLS_PERCENT",n.K);b("I18N_NUMBERFORMATSYMBOLS_ZERO_DIGIT",n.da);b("I18N_NUMBERFORMATSYMBOLS_PLUS_SIGN",n.N);b("I18N_NUMBERFORMATSYMBOLS_MINUS_SIGN",n.F);b("I18N_NUMBERFORMATSYMBOLS_EXP_SYMBOL",n.v);b("I18N_NUMBERFORMATSYMBOLS_PERMILL",n.M);b("I18N_NUMBERFORMATSYMBOLS_INFINITY",n.D);b("I18N_NUMBERFORMATSYMBOLS_NAN",n.H);
b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_PATTERN",n.l);b("I18N_NUMBERFORMATSYMBOLS_SCIENTIFIC_PATTERN",n.P);b("I18N_NUMBERFORMATSYMBOLS_PERCENT_PATTERN",n.L);b("I18N_NUMBERFORMATSYMBOLS_CURRENCY_PATTERN",n.h);b("I18N_NUMBERFORMATSYMBOLS_DEF_CURRENCY_CODE",n.o);b("I18N_COMPACT_DECIMAL_SHORT_PATTERN",d.fa);b("I18N_COMPACT_DECIMAL_LONG_PATTERN",d.ea);
