#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kooha manage=off

# startup
dunst &
$HOME/.config/polybar/scripts/launch.sh &
picom --experimental-backends --config $HOME/.config/picom/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
